objects/Account.object
<CustomObject>
    <fields>
        <fullName>Is_Child__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Child</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>No_Of_Child_Accounts__c</fullName>
        <label>No Of Child Accounts</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/childAccountCreation.cls
public with sharing class childAccountCreation {
public Account acc{set;get;}


List<Account> newRec = new List<Account>();
    public childAccountCreation(ApexPages.StandardController controller) {
        acc = new Account();
    }
    public void myMethod(){
      insert acc;
      if(string.isNotBlank(acc.No_Of_Child_Accounts__c)){
          for(Integer i=0;i<Integer.valueOf(acc.No_Of_Child_Accounts__c);i++){
              Account a = new Account();
              a.Name = acc.Name;
              a.AccountNumber = acc.AccountNumber;
              a.ParentId = acc.Id;
              a.Is_Child__c = true;
              newRec.add(a);
          
          }
          insert newRec;
      
      
      }
    
    }

}