objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/District__c.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>District</relationshipLabel>
        <relationshipName>District</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>District</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/State__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>State</relationshipLabel>
        <relationshipName>State</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>State</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/dependentPicklistrenderex.cls
public class dependentPicklistrenderex {

  
    public String statId { get; set; }
    public String counId { get; set; }
    public List<selectOption> options1{set;get;}
    public List<SelectOption> options2{set;get;}

    public List<selectOption> getItems() {
        List<selectOption> options = new List<selectOption>();
        for(Country__C coun:[select id,Name from Country__c Limit 5]){
            options.add(new SelectOption(coun.Id,coun.Name));
        }
        return options;
    }
    
    public void StateValues(){
        options1 = new List<selectOption>();
        for(State__c stat :[Select Id,Name from State__c where Country__c=:counId]){
            options1.add(new SelectOption(stat.Id,stat.Name));
        }
       
    }
    
      public void DistValues() {
        options2 = new List<selectOption>();
          for(District__c dist:[Select Id,Name from District__c where State__c=:statId]){
              options2.add(new SelectOption(dist.Id,dist.Name));
          }
        
    }


}