objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Student Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/insertExample.cls
public class insertExample {
    
    public void mymethod(List<String> ls ){
        List<Student__c> student = new List<Student__c>();
        if(ls != null && !ls.isEmpty()){
            for(string s : ls){
                Student__c stu = new Student__c();
                stu.First_Name__c = s;
                student.add(stu);
                
                
            }
               insert student; 
                System.debug('Student rec'+student);  
            }
            
        }
    }